apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: whois-servicemonitor
  # Change this to the namespace the Prometheus instance is running in
  # namespace: default
  labels:
    app: whois
    release: prometheus-grafana 
spec:
  selector:
    matchLabels:
      # app: whois
      # release: prometheus-grafana
      app: whois
  endpoints:
  - port: whois
    interval: 15s
    path: /metrics
    