## deploy nginx in the nginx namespace 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/w7l1m7g5/nginx:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "50Mi"
            cpu: "130m"
          limits:
            memory: "64Mi"
            cpu: "1600m"
